### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by lxgbrl** [camenduru/TripoSR-jupyter#2]
Hi, I tried to run this in colab but I get this error:
`
Traceback (most recent call last):
  File "/content/TripoSR-hf/app.py", line 13, in <module>
    from tsr.system import TSR
  File "/content/TripoSR-hf/tsr/system.py", line 16, in <module>
    from .models.isosurface import MarchingCubeHelper
  File "/content/TripoSR-hf/tsr/models/isosurface.py", line 6, in <module>
    from torchmcubes import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/torchmcubes/__init__.py", line 2, in <module>
    import torchmcubes_module as mc
ImportError: /usr/local/lib/python3.10/dist-packages/torchmcubes_module.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
`

Any idea how to solve ?

**Comment by eleven-monkey** [comment]
me too!

**Comment by lxgbrl** [comment]
`
%cd /content
!git clone -b dev https://github.com/camenduru/TripoSR-hf
%cd /content/TripoSR-hf

#!pip install -q trimesh omegaconf einops rembg gradio
#!pip install -q https://github.com/camenduru/wheels/releases/download/colab/torchmcubes-0.1.0-cp310-cp310-linux_x86_64.whl

!pip install -r /content/TripoSR-hf/requirements.txt

#!apt -y install -qq aria2
#!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/stabilityai/TripoSR/resolve/main/model.ckpt -d /content/model -o model.ckpt

%cd /content/TripoSR-hf
!python app.py
`

That was doing it, but without the wheel.
